services:
    hub:
        image: selenium/hub:latest
        platform: linux/amd64  # Fix for Apple Silicon
        container_name: selenium-hub
        ports:
            - "4444:4444"
        environment:
            - GRID_MAX_SESSION=16
            - GRID_BROWSER_TIMEOUT=300
            - GRID_TIMEOUT=300
        networks:
            - selenium-grid

    chrome:
        image: selenium/node-chrome:latest
        platform: linux/amd64  # Fix for Apple Silicon
        shm_size: '2g'
        deploy:
            replicas: 0
        depends_on:
            - hub
        env_file: .env
        networks:
            - selenium-grid

    firefox:
        image: selenium/node-firefox:latest
        platform: linux/amd64  # Fix for Apple Silicon
        shm_size: '2g'
        deploy:
            replicas: 0
        depends_on:
            - hub
        env_file: .env
        security_opt:
            - seccomp:unconfined  # Helps with Firefox sandboxing issues
        networks:
            - selenium-grid

networks:
    selenium-grid:
        driver: bridge